# Generated by Django 5.2.1 on 2025-06-27 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='joined_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_goal', to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='groups.group')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('group', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='GroupMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_current_thoughts', models.TextField(default='', help_text='グループワークのテーマや課題について、今考えていることや、ふと気づいたことなど', verbose_name='現在の思考・気づき')),
                ('key_points_to_focus', models.TextField(blank=True, help_text='グループワークで特に意識したい点、深掘りしたいテーマ、自分の役割で重視したいこと', verbose_name='重視するポイント')),
                ('questions_to_explore', models.TextField(blank=True, help_text='自分の中でまだ明確になっていない疑問、グループで一緒に考えたい問い', verbose_name='探求したい疑問')),
                ('my_initial_contribution', models.TextField(blank=True, help_text='グループワークで自分が具体的にどのように貢献できそうか、役割イメージなど', verbose_name='最初の貢献イメージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_memos', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memos', to='groups.group')),
                ('weekly_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='groups.weeklygoal', verbose_name='関連する週間目標')),
            ],
        ),
        migrations.CreateModel(
            name='MemoAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_week_start', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_assignments', to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='groups.groupmemo')),
            ],
            options={
                'ordering': ['-assignment_week_start', 'memo__my_current_thoughts'],
                'unique_together': {('memo', 'assigned_to', 'assignment_week_start')},
            },
        ),
        migrations.CreateModel(
            name='GroupMemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.role')),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
