# Generated by Django 5.2.1 on 2025-07-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_personalevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoassignment',
            options={'ordering': ['-assignment_week_start', 'memo__talking_points']},
        ),
        migrations.RemoveField(
            model_name='groupmemo',
            name='key_points_to_focus',
        ),
        migrations.RemoveField(
            model_name='groupmemo',
            name='my_current_thoughts',
        ),
        migrations.RemoveField(
            model_name='groupmemo',
            name='my_initial_contribution',
        ),
        migrations.RemoveField(
            model_name='groupmemo',
            name='questions_to_explore',
        ),
        migrations.AddField(
            model_name='groupmemo',
            name='examples_episodes',
            field=models.TextField(blank=True, help_text='話を裏付ける具体的な例や体験談', verbose_name='具体例・エピソード'),
        ),
        migrations.AddField(
            model_name='groupmemo',
            name='reasons_background',
            field=models.TextField(blank=True, help_text='その結論に至った理由や、背景にある情報、データなど', verbose_name='理由・背景'),
        ),
        migrations.AddField(
            model_name='groupmemo',
            name='talking_points',
            field=models.TextField(default='', help_text='グループワークで伝えたい、一番重要な結論や要点', verbose_name='話すポイント(結論)'),
        ),
        migrations.CreateModel(
            name='WeeklyMemoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='週の開始日')),
                ('is_required_this_week', models.BooleanField(default=True, verbose_name='今週のメモは必須か？')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_memo_settings', to='groups.group')),
            ],
            options={
                'verbose_name': '週次メモ設定',
                'verbose_name_plural': '週次メモ設定',
                'ordering': ['-week_start_date'],
                'unique_together': {('group', 'week_start_date')},
            },
        ),
    ]
