# Generated by Django 5.2.1 on 2025-07-01 10:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_memoassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmemo',
            options={'ordering': ['-week_start_date', 'created_by__username']},
        ),
        migrations.AddField(
            model_name='groupmemo',
            name='week_start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='対象週の開始日'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmemo',
            unique_together={('group', 'created_by', 'week_start_date')},
        ),
        migrations.DeleteModel(
            name='MemoAssignment',
        ),
    ]
