# Generated by Django 5.2.1 on 2025-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupmemo_options_groupmemo_week_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmemo',
            name='week_start_date',
            field=models.DateField(verbose_name='対象週の開始日'),
        ),
    ]
